- hosts: all
  become: true
  pre_tasks:
    - name: Run apt update before installing prerequisites
      apt:
        update_cache: yes

  roles:
    - role: setup
    
    - role: volumes
      when: instance_store_enabled | default(false) | bool

    - role: christiangda.amazon_cloudwatch_agent
      when: cloudwatch_enable | default(false) | bool
      vars:
        cwa_agent_mode: "ec2"
        cwa_conf_json_file_content: "{{ lookup('file', 'files/CloudWatch.json') | from_json }}"
      
    - role: "dev-sec.os-hardening"
      when: ansible_hardening | default(false) | bool

    - role: "dev-sec.ssh-hardening"
      when: ansible_hardening | default(false) | bool

    - role: geerlingguy.docker
      update_cache: yes

    - role: fubarhouse.golang
      vars:
        go_version: 1.16.2

    - role: ansible-role-icon-prep
#    - role: icon-prep

  vars:
    docker_users:
      - "{{ admin_user | default('ubuntu') }}"
